[build]
  command = "npm install"
  functions = "netlify/functions" # Directory for Netlify functions
  publish = "public"             # Directory for static files

[dev]
  command = "npm run start"
  framework = "#custom"
